In [3]:
# Python code
result = 0
for i in range(100):
    result += i

In [4]:
# Python code
x = 4
x = "four"

# A python integer is more than aan integer :v

A single integer in Python 3.4 actually contains four pieces:

ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation

ob_type, which encodes the type of the variable

ob_size, which specifies the size of the following data members

ob_digit, which contains the actual integer value that we expect the Python variable to represent.



# A Python List Is More Than Just a List

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [8]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2[0])

str

In [10]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [11]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np


# Creating Arrays from Python Lists

In [15]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

# Fixed-Type Arrays in Python

In [22]:
import array
# python list
L = list(range(10))
# array
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
import numpy as np


# Creating Arrays from Python Lists

In [28]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [29]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [31]:
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [32]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [35]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.19709388, 0.01448513, 0.96389958],
       [0.76509071, 0.35826098, 0.64231148],
       [0.96505779, 0.7894222 , 0.00119016]])

In [38]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.04012788,  1.39198095,  0.80011764],
       [-0.29522875,  2.14253473, -1.05673731],
       [-0.63226355, -0.5184721 ,  1.38867667]])

In [39]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 5, 5],
       [9, 2, 4],
       [0, 6, 6]])

In [40]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])