# NumPy Array Attributes

In [42]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [43]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [44]:
print("dtype:", x3.dtype)


dtype: int64


In [45]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


# Array Indexing: Accessing Single Elements

In [46]:
x1

array([5, 0, 3, 3, 7, 9])

In [48]:
x1[-1]

9

In [49]:
x1[-2]

7

In [50]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
x2[0, 0]

3

# Array Slicing: Accessing Subarrays

In [52]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [54]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [55]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [60]:
x[::4]  # every other element

array([0, 4, 8])

In [61]:
x[1::2]  # every other element, starting at index 1


array([1, 3, 5, 7, 9])

In [62]:
x[::-1]  # all elements, reversed


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [65]:
x[5::-2]  # reversed every other from index 5


array([5, 3, 1])

# Multi-dimensional subarrays

In [66]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [67]:
x2[:2, :3]  # two rows, three columns


array([[3, 5, 2],
       [7, 6, 8]])

In [68]:
x2[:3, ::2]  # all rows, every other column


array([[3, 2],
       [7, 8],
       [1, 7]])

In [69]:
x2[::-1, ::-1]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [70]:
print(x2[:, 0])  # first column of x2


[3 7 1]


In [71]:
print(x2[0, :])  # first row of x2


[3 5 2 4]


In [72]:
print(x2[0])  # equivalent to x2[0, :]


[3 5 2 4]


# Subarrays as no-copy views

In [73]:
print(x2)


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [74]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [75]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [76]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Creating copies of arrays

In [77]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [78]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [79]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of Arrays

In [80]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [82]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [83]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [84]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of arrays¶

In [85]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [86]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [87]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [88]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [90]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [91]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

In [92]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [93]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [95]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [96]:
x1[:]

array([1, 2, 3])