# Summing the Values in an Array

In [1]:
import numpy as np


In [2]:
L = np.random.random(100)
sum(L)


48.81348297907171

In [3]:
np.sum(L)


48.81348297907171

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

49.5 ms ± 67.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
152 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Minimum and Maximum

In [5]:
min(big_array), max(big_array)


(5.396783913647063e-06, 0.9999998136110525)

In [6]:
np.min(big_array), np.max(big_array)


(5.396783913647063e-06, 0.9999998136110525)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

38.2 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
91 µs ± 1.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
print(big_array.min(), big_array.max(), big_array.sum())


5.396783913647063e-06 0.9999998136110525 499596.5038920975


## Multi dimensional aggregates

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.34360642 0.02744559 0.4129916  0.50305214]
 [0.09675232 0.86066741 0.8454281  0.15974737]
 [0.02345802 0.73704003 0.97378414 0.00103414]]


In [10]:
M.sum()


4.985007263029129

In [11]:
M.min(axis=0)


array([0.02345802, 0.02744559, 0.4129916 , 0.00103414])

In [14]:
M.max(axis=1)


array([0.50305214, 0.86066741, 0.97378414])