## Introducing Broadcasting

Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

In [2]:
import numpy as np


In [3]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
a + 5


array([5, 6, 7])

In [5]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
M + a


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

### Broadcasting example 1

Let's look at adding a two-dimensional array to a one-dimensional array:

In [7]:
M = np.ones((2, 3))
a = np.arange(3)

In [8]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])